version: '3.8'

services:
  spring-h2:
    image: spring-h2-app
    build: .
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:springh2
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update