name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test
        run: ./mvnw clean package -DskipTests

      - name: Run Tests
        run: ./mvnw test

      # Optional: Setup Docker Build if your project is containerized
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag your-username/your-repo:${{ github.sha }}